### ISSUE TITLE
Pantalla de splashscreen

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#29]
Crear un nuevo html y controller, splash.js / splash.html

En splash.html agregar:
``` html
<ion-view title="Inicio" has-footer="false" class="fullscreen-image" hide-nav-bar="true">

</ion-view>
```

En style.css agregar:
``` css
.fullscreen-image {
    background: url(../img/splash2.png) no-repeat center center fixed;
    -webkit-background-size: contain;
    -moz-background-size: contain;
    background-size: contain;
}
```
Como imagen utilizar por el momento el logo de crear.
Cada vez que se necesitan escribir las huellas en el lector, redireccionar a esta pantalla y que se carguen llamando al servicio desde aquí.

Idealmente, agregarle un ionicloading donde se muestre el progreso (Cuantas huellas se grabaron del total). Acá hay algunos tips: 
https://forum.ionicframework.com/t/progress-bar-using-ionic-framework/574/3
